version: "3.1"
services:
  api:
    build: .
    image: url_shortener
    expose:
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - .:/url_shortener:ro  
    depends_on: 
      - db  
  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - 0.0.0.0:5432:5432  
    volumes:
      - db_data_url:/var/lib/postgresql/data  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shriank987
    
volumes:
  db_data_url: