"""create url_mapper table

Revision ID: e7d8aa69fc19
Revises: 
Create Date: 2023-11-26 23:12:45.123792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d8aa69fc19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mappers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('short_url', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_url_mappers'))
    )
    op.create_index(op.f('ix_url_mappers_short_url'), 'url_mappers', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_mappers_short_url'), table_name='url_mappers')
    op.drop_table('url_mappers')
    # ### end Alembic commands ###
